routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Auth::routes();
// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');
// // Password Reset Routes...
// Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
// Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
// Route::post('password/reset', 'Auth\ResetPasswordController@reset');
// Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::get('/success', 'Auth\RegisterController@success')->name('success');

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['prefix' => 'nodes', 'as' => 'nodes.'], function () {
    Route::get('/', 'NodesController@index')->name('index');
    Route::get('/{id}/show', 'NodesController@show')->name('show');
    Route::get('/datatable', 'NodesController@dataTable')->name('datatable');
});

Route::group(['prefix' => 'my-nodes', 'as' => 'my.nodes.'], function () {
    Route::get('/', function () {
        return view('pages.my-nodes.index');
    })->name('index');
    Route::get('/detail', function () {
        return view('pages.my-nodes.show');
    })->name('show');
});

Route::group(['prefix' => 'balances', 'as' => 'balances.'], function () {
    Route::get('/', 'BalancesController@index')->name('index');
    Route::get('/{id}/show', 'BalancesController@show')->name('show');
    Route::get('/datatable', 'BalancesController@dataTable')->name('datatable');
});

app/Models/Node.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Node extends Model
{
    protected $table = 'mn_master';
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The table used
     */
    protected $table = 'usermaster';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'email', 'password', 'dob', 'active', 'activation_code', 'reset_token',
        'token_expire', 'enable2fa', 'created_by', 'updated_by'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/BalancesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Services\BalanceServices;

class BalancesController extends Controller
{
    public function index()
    {
        return view('pages.balances.index');
    }

    public function show($id)
    {
        return view('pages.balances.show');
    }

    public function dataTable()
    {
        $balanceServices = new BalanceServices('user_wallet');
        return $balanceServices->getTable();
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/NodesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Services\NodesServices;

class NodesController extends Controller
{
    
    public function __construct()
    {
        return $this->middleware('auth');
    }

    /**
     * Display Master node index
     *
     * @return void
     */
    public function index()
    {
        return view('pages.nodes.index');
    }

    /**
     * Show Master Node Detail
     *
     * @param [type] $id
     * @return void
     */
    public function show($id)
    {
        $nodesServices = new NodesServices('mn_master');
        $data = $nodesServices->getShow($id);
        return view('pages.nodes.show', compact('data'));
    }

    /**
     * JSON DataTable Method 
     *
     * @return JSON
     */
    public function dataTable()
    {
        $nodesServices = new NodesServices('mn_master');
        return $nodesServices->getTable();
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<section class="content">
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2>Home
                    <small>Welcome to Nodemaster</small>
                </h2>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
                <ul class="breadcrumb float-md-right">
                    <li class="breadcrumb-item"><a href="index.html"><i class="zmdi zmdi-home"></i> Nodemaster</a></li>
                    <li class="breadcrumb-item"><a href="javascript:void(0);">Dashboard</a></li>
                    <li class="breadcrumb-item active">Home</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-12">
                <div class="card">
                    <div class="body">
                        <div class="col-xs-1 text-center">
                            <h3><strong>Join New</strong> Masternode</h3>
                            <a href="{{ route('nodes.index') }}" class="btn btn-info btn-round ">Click Here</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    <div class="header">
                        <h2><strong>Active Masternode</strong></h2>
                    </div>
                    <div class="body table-responsive">
                        <table class="table">
                            <thead class="bg-info text-white">
                                <tr>
                                    <th>Name</th>
                                    <th>MasternodeID</th>
                                    <th>Amount Reserved</th>
                                    <th>Last Payout</th>
                                    <th>Detail</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th scope="row">ACOIN</th>
                                    <td>MN0001</td>
                                    <td>100</td>
                                    <td>2018-04-03</td>
                                    <td><a href="#">-></a></td>
                                </tr>
                                <tr>
                                    <th scope="row">BCOIN</th>
                                    <td>MN0002</td>
                                    <td>30</td>
                                    <td>2018-04-05</td>
                                    <td><a href="#">-></a></td>
                                </tr>
                                <tr>
                                    <th scope="row">ACOIN</th>
                                    <td>MN0015</td>
                                    <td>1500</td>
                                    <td>2018-04-15</td>
                                    <td><a href="#">-></a></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html class="no-js " lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <meta name="description" content="Masternode Website">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    
    <title>{{ config('app.name', 'Laravel') }}</title>
    <!-- Favicon-->
    <link rel="icon" href="{{ asset('assets/images/favicon.ico') }}" type="image/x-icon">
    <!-- Custom Css -->
    <link rel="stylesheet" href="{{ asset('assets/plugins/bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/main.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/color_skins.css') }}">
    @stack('styles')
</head>

<body class="theme-blue">
    <!-- Page Loader -->
    <div class="page-loader-wrapper">
        <div class="loader">
            <div class="m-t-30"><img class="zmdi-hc-spin" src="{{ asset('assets/images/logo.svg') }}" width="48" height="48" alt="Mnode"></div>
            <p>Please wait...</p>
        </div>
    </div>

    <!-- Overlay For Sidebars -->
    <div class="overlay"></div>

    <!-- Top Bar -->
    @include('layouts.partials._topbar')

    <!-- Left Sidebar -->
    @include('layouts.partials._sidebar')

    <!-- Main Content -->
    @yield('content')
    <!-- Jquery Core Js -->
    <script src="{{ asset('assets/bundles/libscripts.bundle.js') }}"></script>
    <!-- Lib Scripts Plugin Js -->
    <script src="{{ asset('assets/bundles/vendorscripts.bundle.js') }}"></script>
    <!-- Lib Scripts Plugin Js -->
    <script src="{{ asset('assets/bundles/mainscripts.bundle.js') }}"></script>
    @stack('scripts')
</body>
</html>

resources/views/layouts/partials/_sidebar.blade.php
<aside id="leftsidebar" class="sidebar">
    <ul class="nav nav-tabs">
        <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#dashboard"><i class="zmdi zmdi-home m-r-5"></i>Home</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane stretchRight active" id="dashboard">
            <div class="menu">
                <ul class="list">
                    <li class="header">MAIN</li>
                    <li> <a href="{{ route('home') }}"><i class="zmdi zmdi-home"></i><span>Dashboard</span></a></li>
                    <li> <a href="javascript:void(0);" class="menu-toggle"><i class="zmdi zmdi-apps"></i><span>Nodes</span> </a>
                        <ul class="ml-menu">
                            <li><a href="{{ route('nodes.index') }}">Join New Nodes</a></li>
                            <li><a href="{{ route('my.nodes.index') }}">My Nodes</a></li>
                        </ul>
                    </li>
                    <li> <a href="javascript:void(0);" class="menu-toggle"><i class="zmdi zmdi-apps"></i><span>Balance</span> </a>
                        <ul class="ml-menu">
                            <li><a href="{{ route('balances.index') }}">My Balance</a></li>
                        </ul>
                    </li>
                    <li class="header">EXTRA</li>
                    <li> <a href="setting.html"><i class="zmdi zmdi-settings"></i><span>Setting</span></a></li>
                    <li> 
                        <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            <i class="zmdi zmdi-power"></i>
                            <span>Logout</span>
                        </a>
                    </li>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        {{ csrf_field() }}
                    </form>
                </ul>
            </div>
        </div>
    </div>
</aside>

resources/views/layouts/partials/_topbar.blade.php
<nav class="navbar p-l-5 p-r-5">
    <ul class="nav navbar-nav navbar-left">
        <li>
            <div class="navbar-header">
                <a href="javascript:void(0);" class="bars"></a>
                <a class="navbar-brand" href="index.html"><img src="{{ asset('assets/images/logo.svg') }}" width="30" alt="Nodemaster"><span class="m-l-10">Nodemaster</span></a>
            </div>
        </li>
        <li><a href="javascript:void(0);" class="ls-toggle-btn" data-close="true"><i class="zmdi zmdi-swap"></i></a></li>
        <li class="float-right">
            <a href="javascript:void(0);" class="fullscreen hidden-sm-down" data-provide="fullscreen" data-close="true"><i class="zmdi zmdi-fullscreen"></i></a>
        </li>
    </ul>
</nav>

resources/views/pages/balances/index.blade.php
@extends('layouts.app')

@push('styles')
    <!-- JQuery DataTable Css -->
    <link rel="stylesheet" href="{{ asset('assets/plugins/jquery-datatable/dataTables.bootstrap4.min.css') }}">
    <style type="text/css">   
        .col-centered {
            float: none;
            margin: 0 auto;
        }
    </style>
@endpush

@section('content')
<section class="content">
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2>My Balance
                <small>Welcome to Nodemaster</small>
                </h2>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
                <ul class="breadcrumb float-md-right">
                    <li class="breadcrumb-item"><a href="index.html"><i class="zmdi zmdi-home"></i> Nodemaster</a></li>
                    <li class="breadcrumb-item"><a href="javascript:void(0);">Dashboard</a></li>
                    <li class="breadcrumb-item active">My Balance</li>
                </ul>                
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <!-- Basic Examples -->
        <div class="row clearfix">
            <div class="col-lg-12">
                <div class="card">
                    <div class="body table-responsive">
                        <div class="col-lg-4 col-centered">
                            <h3><strong>My</strong> Balances </h3>
                        </div>
                        <table class="table table-bordered table-striped table-hover js-basic-example dataTable" id="dataTable">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Balance Available</th>
                                    <th>Balance Pending</th>
                                    <th>Balance Masternode</th>
                                    <th>Detail</th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th>Name</th>
                                    <th>Balance Available</th>
                                    <th>Balance Pending</th>
                                    <th>Balance Masternode</th>
                                    <th>Detail</th>
                                </tr>
                            </tfoot>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <!-- #END# Basic Examples --> 
    </div>
</section>
@endsection

@push('scripts')
    <!-- Jquery DataTable Plugin Js -->
    <script src="{{ asset('assets/bundles/datatablescripts.bundle.js') }}"></script>
    <!-- Custom Js -->
    <script type="text/javascript">
       $(function () { 
            $('#dataTable').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('balances.datatable') }}",
                columns: [
                    {data: 'ticker', name: 'ticker'},
                    {data: 'amount_available', name: 'amount_available'},
                    {data: 'amount_lock', name: 'amount_lock'},
                    {data: 'amount_mn', name: 'amount_mn'},
                    {data: 'detail', name: 'detail'}
                ]
            }); 
        });
    </script>
@endpush

resources/views/pages/balances/show.blade.php
@extends('layouts.app')

@push('styles')
    <style type="text/css">    
        .col-centered {
            float: none;
            margin: 0 auto;
        }
    </style>
@endpush 

@section('content')
<section class="content">
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2>Acoin Balance
                <small>Welcome to Nodemaster</small>
                </h2>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
                <ul class="breadcrumb float-md-right">
                    <li class="breadcrumb-item"><a href="index.html"><i class="zmdi zmdi-home"></i> Nodemaster</a></li>
                    <li class="breadcrumb-item"><a href="javascript:void(0);">Dashboard</a></li>
                    <li class="breadcrumb-item active">Acoin Balance</li>
                </ul>                
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    <div class="body table-responsive">
                        <div class="col-lg-4 col-centered">
                            <h3><strong>ACOIN</strong> Balance </h3>
                        </div>

                        <h6>Acoin Address</h6>
                         <div class="col-lg-4">
                            <div class="form-group">
                                <div class="input-group">
                                  <input type="text" name="address" value="0xABCDE1134DDFF3424099BDF" id="address" class="form-control" placeholder="Address" aria-label="address" aria-describedby="basic-addon2">
                                  <div class="input-group-append">
                                    <button class="btn btn-outline-secondary btn-round btn-copy" type="button" data-clipboard-target="#address" data-toggle="tooltip" title="Copy to Clipboard">Copy</button>
                                  </div>
                                </div>
                            </div>
                        </div>
                        <br>

                        <h6>Balance Detail</h6>
                        <p>Balance Available <span class="tab">: <strong>70 ACOIN</strong> <button class="btn btn-sm btn-info btn-round">Withdraw</button></span></p>
                        <p>Balance Pending <span class="tab">: <strong>150 ACOIN</strong> <a href="#" data-toggle="tooltip" title="Balance Pending is your balance queued for upcoming masternode">(?)</a> <button class="btn btn-sm btn-info btn-round">Withdraw</button></span></p>
                        <p>Balance in Master Node <span class="tab">: <strong>3000 ACOIN</strong> <button class="btn btn-sm btn-info btn-round">Detail</button></span></p>
                        <br>

                        <h6>History</h6>
                        <div class="body table-responsive">
                        <table class="table">
                            <thead class="bg-info text-white">
                                <tr>
                                    <th>Date</th>
                                    <th>Trx Type</th>
                                    <th>Amount</th>
                                    <th>Additional Info</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th scope="row">2018-04-12 20:30</th>
                                    <td>MN Payout</td>
                                    <td>70</td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <th scope="row">2018-04-08 19:30</th>
                                    <td>Transfer In</td>
                                    <td>70</td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <th scope="row">2018-04-12 20:30</th>
                                    <td>Transfer In</td>
                                    <td>70</td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <th scope="row">2018-04-12 20:30</th>
                                    <td>Transfer In</td>
                                    <td>70</td>
                                    <td></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

@push('scripts')
    <script src="{{ asset('assets/plugins/clipboardjs/clipboard.min.js') }}"></script>
    <script type="text/javascript">
        $(function () {
            $('[data-toggle="tooltip"]').tooltip();
        })

        function setTooltip(btn, message) {
            $(btn).tooltip('hide')
            .attr('data-original-title', message)
            .tooltip('show');
        }

        function hideTooltip(btn) {
            setTimeout(function() {
                $(btn).tooltip('hide');
            }, 1000);
        }

        // Clipboard

        var clipboard = new ClipboardJS('button');

        clipboard.on('success', function(e) {
            setTooltip(e.trigger, 'Copied!');
            hideTooltip(e.trigger);
        });

        clipboard.on('error', function(e) {
            setTooltip(e.trigger, 'Failed!');
            hideTooltip(e.trigger);
        });
    </script>
@endpush

resources/views/pages/my-nodes/index.blade.php
@extends('layouts.app')

@push('styles')
<!-- JQuery DataTable Css -->
<style type="text/css">
    .col-centered {
        float: none;
        margin: 0 auto;
    }
</style>
@endpush

@section('content')
<section class="content">
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2>Home
                    <small>Welcome to Nodemaster</small>
                </h2>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
                <ul class="breadcrumb float-md-right">
                    <li class="breadcrumb-item"><a href="index.html"><i class="zmdi zmdi-home"></i> Nodemaster</a></li>
                    <li class="breadcrumb-item"><a href="javascript:void(0);">Dashboard</a></li>
                    <li class="breadcrumb-item active">Home</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    <div class="body table-responsive">
                        <div class="col-lg-4 col-centered">
                            <h3><strong>My</strong> Masternode </h3>
                        </div>
                        <table class="table">
                            <thead class="bg-info text-white">
                                <tr>
                                    <th>Name</th>
                                    <th>MasternodeID</th>
                                    <th>Amount Reserved</th>
                                    <th>Last Payout</th>
                                    <th>Detail</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th scope="row">ACOIN</th>
                                    <td>MN0001</td>
                                    <td>100</td>
                                    <td>2018-04-03</td>
                                    <td><a href="{{ route('my.nodes.show') }}">-></a></td>
                                </tr>
                                <tr>
                                    <th scope="row">BCOIN</th>
                                    <td>MN0002</td>
                                    <td>30</td>
                                    <td>2018-04-05</td>
                                    <td><a href="{{ route('my.nodes.show') }}">-></a></td>
                                </tr>
                                <tr>
                                    <th scope="row">ACOIN</th>
                                    <td>MN0015</td>
                                    <td>1500</td>
                                    <td>2018-04-15</td>
                                    <td><a href="{{ route('my.nodes.show') }}">-></a></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/pages/nodes/index.blade.php
@extends('layouts.app')

@push('styles')
    <!-- JQuery DataTable Css -->
    <link rel="stylesheet" href="{{ asset('assets/plugins/jquery-datatable/dataTables.bootstrap4.min.css') }}">
    <style type="text/css">   
        .col-centered {
            float: none;
            margin: 0 auto;
        }
    </style>
@endpush

@section('content')
    <section class="content">
        <div class="block-header">
            <div class="row">
                <div class="col-lg-7 col-md-6 col-sm-12">
                    <h2>Join Masternode
                        <small>Welcome to Nodemaster</small>
                    </h2>
                </div>
                <div class="col-lg-5 col-md-6 col-sm-12">
                    <ul class="breadcrumb float-md-right">
                        <li class="breadcrumb-item"><a href="index.html"><i class="zmdi zmdi-home"></i> Nodemaster</a></li>
                        <li class="breadcrumb-item"><a href="javascript:void(0);">Dashboard</a></li>
                        <li class="breadcrumb-item active">Join Masternode</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <!-- Basic Examples -->
            <div class="row clearfix">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="body table-responsive">
                            <div class="col-lg-4 col-centered">
                                <h3><strong>Join</strong> Masternode </h3>
                            </div>
                            <table class="table table-bordered table-striped table-hover" id="dataTable">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Price</th>
                                        <th>Volume</th>
                                        <th>Market Cap</th>
                                        <th>Number of Nodes</th>
                                        <th>Required</th>
                                        <th>Worth</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>Name</th>
                                        <th>Price</th>
                                        <th>Volume</th>
                                        <th>Market Cap</th>
                                        <th>Number of Nodes</th>
                                        <th>Required</th>
                                        <th>Worth</th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Basic Examples -->
        </div>
    </section>
@endsection

@push('scripts')
    <!-- Jquery DataTable Plugin Js -->
    <script src="{{ asset('assets/bundles/datatablescripts.bundle.js') }}"></script>
    <!-- Custom Js -->
    <script type="text/javascript">
        $(function () { 
            $('#dataTable').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('nodes.datatable') }}",
                columns: [
                    {data: 'name', name: 'name'},
                    {data: 'price', name: 'price'},
                    {data: 'volume', name: 'volume'},
                    {data: 'marketcap', name: 'marketcap'},
                    {data: 'num_of_node', name: 'num_of_node'},
                    {data: 'needed', name: 'needed'},
                    {data: 'worth', name: 'worth'},
                ]
            }); 
        });
    </script>
@endpush